### ISSUE TITLE
[Curriculum] HW 04 q1_5

### ISSUE THREAD

**Issue by jdeisenberg** [data-8/materials-sp22#29]
### Assignment Number or lecture
HW04

### Feedback or Suggestion
If I use this solution for Question 5:

```
best_california_burrito = california_burritos.sort("Overall average", descending=True).row(0).item(0)
best_california_burrito
```

Everything looks OK, but the `grader.check("q1_5")` gives this error:

```
❌ Test case failed
    Trying:
        type(best_california_burrito) == str
    Expecting:
        True
    **********************************************************************
    Line 1, in q1_5 0
    Failed example:
        type(best_california_burrito) == str
    Expected:
        True
    Got:
        False
```

It turns out that `row(0).item(0)` returns a `numpy.str_` object, which displays like a regular Python `str`, but isn’t the expected type in the test.

**Comment by sean-morris** [comment]
@jdeisenberg Thanks for this. The difference here is that our solution looks like this:
best_california_burrito = california_burritos.sort("Overall average", descending=True).column("Menu_Item").item(0) 

Here the column() function returns numpy.ndarray and the function item() then extracts the first element as a normal Python str.

In your solution, the function row(0) returns a Row Object and consequently item(0) returns a numpy scalar numpy.str_

I guess we could check for either. I will update the check.

Thanks again
